// import './module/scene'
// import './module/scale'
// import './module/rotation'
// import './module/clock'
// import './module/gsap'
// import './module/orbitControls'
// import './module/fullScreen'
// import './module/dat.gui'
// import './module/bufferGemetory'
// import './module/triangle'
// import './module/texture'
// import './module/texture-mip'
// import './module/texture-transparent'
// import './module/light'
// import './module/loadmanage'
// import './module/light-shadow'
// import './module/spot-light'
import './module/point-light'
